version: '3.4'

services:
  redis_auth:
    image: bitnami/redis:5.0
    environment:
     - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - 7000:6379

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
     - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      
  apiserver:
    image: ${DOCKER_REGISTRY-}apiserver
    build:
      context: .
      dockerfile: ApiServer/Dockerfile
    depends_on:
     - identityserver
    ports:
     - 8081:80    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://identityserver
      
