version: '3.4'

services:
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
     - 8080:80    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      
  apiserver:
    image: ${DOCKER_REGISTRY-}apiserver
    build:
      context: .
      dockerfile: ApiServer/Dockerfile
    depends_on:
     - identityserver
    ports:
     - 8081:80    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://identityserver
      
